# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'


steps:
- task: CondaEnvironment@1
- script: pwd
- script: ls
- script: echo Hello, world!
- script: conda update conda
- script: conda env create -f environment.yml
- script: conda activate cpe
- script: du -hs /usr/share/miniconda/envs
