jobs:

- job: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH
  - script: conda update conda
    displayName: Update conda
  - script: conda env create --file environment.yml
    displayName: Create conda environment
  - script: conda list --name cpe-kaggle
    displayName: Conda list
  - script: |
      call activate cpe-kaggle
      python -c "import fiona; print(fiona.__version__)"
    displayName: Import fiona
  - script: |
      call activate cpe-kaggle
      python -c "import fion; print(fion.__version__)"
    displayName: Import fion

- job: 'macOS'
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - task: CondaEnvironment@1
  - script: conda update conda
    displayName: Update conda
  - script: conda env create --file environment.yml
    displayName: Create conda environment
  - script: conda list --name cpe-kaggle
    displayName: Conda list
