# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

- job: 'macOS build'

  pool:
    vmImage: 'macOS-10.13'
  
  steps:
  - task: CondaEnvironment@1
  
  - script: ls
    displayName: 'List directory'
  
  - script: conda update conda
    displayName: 'Update conda'
  
  - script: conda env create -f environment.yml
    displayName: 'Create environment'
