jobs:
- job: 'macOS'
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - task: CondaEnvironment@1
  - script: ls
    displayName: 'List directory'
  - script: conda update conda
    displayName: 'Update conda'
  - script: conda env create -f environment.yml
    displayName: 'Create environment'
- job: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: CondaEnvironment@1
  - script: dir
    displayName: 'List directory'
  - script: conda update conda
    displayName: 'Update conda'
  - script: conda env create -f environment.yml
    displayName: 'Create environment'
