name: cpe
channels:
  - defaults
dependencies:
  - python=3.7
  - testpath=0.3.*
  - ipython=7.0.*
  - jupyter=1.0.*
  - click=7.0.*
  - pandas=0.23.*
  - pip:
    - httpie==0.9.*
    - kaggle==1.4.*

