name: cpe
channels:
  - defaults
dependencies:
  - python=3.7
  - testpath=0.3.*
  - ipython=7.0.*
  - jupyter=1.0.*
  - click=7.0.*
  - numpy=1.15.*
  - pandas=0.23.*
  - fiona=1.7.*
  - pyproj=1.9.*
  - shapely=1.6.*
  - matplotlib=3.0.*
  - descartes=1.1.*
  - statsmodels=0.9.*
  - scikit-learn=0.20.*
  - pip:
    - doit==0.31.*
    - httpie==0.9.*
    - requests=2.20.*
    - pytest==3.9.*
    - kaggle==1.4.*
    - flake8==3.6.*
    - us==1.0.*
    - pytess=1.0.0

